version: "2"
services:
  haproxy:
    build: haproxy
    links:
      - letsencrypt
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
      - letsencrypt
  letsencrypt:
    build: letsencrypt
    environment:
      - DOMAINS=foo.com,www.foo.com;ba.com,www.bar.com
      - EMAIL=admins@foo.com
      - LOAD_BALANCER_SERVICE_NAME=haproxy
      # THIS IS CRUCIAL when testing to avoid reaching the 5 certificates
      # limit per domain. You'll end up waiting a week before being able 
      # to regenerate a valid cert if you don't backup the once generated
      - OPTIONS=--staging
    expose:
      - "80"
    volumes:
      - ./letsencrypt_backup:/etc/letsencrypt
  web:
    environment:
      - FORCE_SSL=yes
      - VIRTUAL_HOST=http://*,https://*
    image: dockercloud/hello-world:latest